version: '2'
services:
  monitor-docker:
    container_name: monitor-docker
    image: poohsen/monitor-docker:latest
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      IFTTT_EVENT_NAME: "$IFTTT_EVENT_NAME"
      IFTTT_SERVICE_KEY: "$IFTTT_SERVICE_KEY"
      MSG_PREFIX: "$MSG_PREFIX"
    restart: always
